config/routes.rb
Rails.application.routes.draw do

  root to: "application#contacts"

  get "/agenda", to: "application#agenda"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require "open-uri"

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :contacts
  has_many :events

  def self.find_for_google_oauth2(oauth, signed_in_resource=nil)
    credentials = oauth.credentials
    data = oauth.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(
        first_name: data["first_name"],
        last_name: data["first_name"],
        picture: data["image"],
        email: data["email"],
        password: Devise.friendly_token[0,20],
        token: credentials.token,
        refresh_token: credentials.refresh_token
      )
    end
    # user.get_google_contacts
    # user.get_google_calendars
    user.load_events
    user
  end

  def load_events
    begin
      client = self.create_client
      service = client.discovered_api('calendar', 'v3')
      calendars = client.execute(
        :api_method => service.events.list,
        :parameters => list_parameters
      )
      calendars.data.items
    rescue Faraday::Error::ConnectionFailed => e
      puts e
    rescue Exception => e
      puts e
    end
  end
  
  def create_client
    client = Google::APIClient.new(application_name: "rails-google-calendars", application_version: 3.0)
    client.authorization.access_token = self.token
    client.authorization.refresh_token = self.refresh_token if self.refresh_token
    client.auto_refresh_token=true
    client
  end

  def list_parameters
    parameters = {
      'calendarId' => self.email,
      'showDeleted': true,
      'maxResults': 10
    }
    parameters
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def contacts
  end
  def agenda
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/agenda.html.erb
<div class="row">
  <div class="col-xs-2">
    <ul class="nav nav-pills nav-stacked">
      <li><%= link_to "Contacts", root_path%></li>
      <li class="active"><%= link_to "Agenda", agenda_path%></li>
    </ul>
  </div>

  <div class="col-xs-10">

    <table class='table table-striped'>

      <tr>
        <th class="text-center">Name</th class="text-center">
        <th class="text-center">Date</th>
        <th class="text-center">Creator</th>
        <th class="text-center">Calendar</th>
        <th class="text-center">link</th>
      </tr>

      <% current_user.events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.start %></td>
          <td><%= event.creator %></td>
          <td><%= event.calendar %></td>
          <td><%= link_to "#{event.name.first(10)}...", event.link %></td>
        </tr>
      <% end %>

    </table>


  </div>
</div>

app/views/application/contacts.html.erb
<div class="row">
  <div class="col-xs-2">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><%= link_to "Contacts", root_path%></li>
      <li><%= link_to "Agenda", agenda_path%></li>
    </ul>
  </div>

  <div class="col-xs-10">

    <table class='table table-striped'>

      <tr>
        <th class="text-center">Email</th>
        <th class="text-center">Contact</th>
        <th class="text-center">Tel</th>
        <th class="text-center">Picture</th>
      </tr>

      <% current_user.contacts.each do |contact| %>
        <tr>
          <td><%= contact.email %></td>
          <td><%= contact.name %></td>
          <td><%= contact.tel %></td>
          <td>
            <% unless contact.picture %>
              <i class="fa fa-user fa-4"></i>
            <% else %>
              <%= image_tag contact.picture, width: "50px"%>
            <% end %>
          </td>
        </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoogleCalApi</title>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="#">GOOGLE-CONNECT</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag current_user.picture, class: "img img-circle", width: "50px"%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <div class="container text-center">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>


</body>
</html>